### ISSUE TITLE
infra: deprecation and cleanup plan

### ISSUE THREAD

**Issue by aarnphm** [bentoml/OpenLLM#513]
This is part 1 of an internal refactoring to provide a nicer and flexible API for users to use LLM

Note that these are mostly internal changes, and hopefully it shouldn't affect users too much.

# Proposal

```python
import openllm

llm = openllm.LLM('meta-llama/Llama-2-7b-hf-chat')
```

By default, `llm.generate` and `llm.generate_iterator` will be async functions. Users can use `llm.sync_generate` and `llm.sync_generate_iterator` to get the sync version.

```python
# async def llm.generate(*args, **kwargs) -> openllm.GenerationOutput: ...
one_shot = await llm.generate("Hello World")
```

```python
# async def llm.generate_iterator(*args, **kwargs) -> t.Iterator[openllm.GenerationOutput]: ...
async for generated in llm.generate_iterator("Hello World"): print(generated)
```

For using with BentoML service code, one can do the following:

```python title="llm_service.py"

import openllm

llm = openllm.LLM('meta-llama/Llama-2-7b-hf-chat')
svc = bentoml.Service('chat', runners=[llm.runner])

@svc.api(input=bentoml.io.Text(), output=bentoml.io.JSON())
def chat(text): return llm.generate(text)
```

> [!IMPORTANT]
> `openllm.LLM` will now hold a reference to the model and tokenizer, and model will be loaded once when inference is called

> [!IMPORTANT]
> The model will now be its own runner,  which will be managed internally by `openllm.LLM`. Tokenizer will become embedded runners

Therefore, `openllm.Runner` is now deprecated, and will be removed in the future.

I will try not to make breaking changes to `openllm.Runner`.

# API Deprecation

We will also deprecate Flax and TF backend support, and only support vLLM and PyTorch for the time being.
The reason being that we want to focus on providing a good API for users to use LLM, and we don't have the bandwidth to support 4 backends, as the matrix grows big quickly.

We will also now fully focus on supporting a few targeted model architectures (Llama-2, Mistral (wip), ChatGLM), and will kindly move all of the remaining architecture to best-effort support.

# TODO
- [ ] Remove Auto classes abstraction
- [ ] Cleanup  `openllm.LLM` API, and expose the class
- [ ] Update redirection of `openllm.Runner` to use `openllm.LLM` logic

**Comment by aarnphm** [comment]
This is now merged and finished.
